### ISSUE TITLE
How to use with ORM?

### ISSUE THREAD

**Issue by graup** [pyeventsourcing/eventsourcing-django#10]
Hi! I'm new to eventsourcing. The Readme says "This package supports using the Python eventsourcing library ***with Django ORM***." Could you provide examples of how this works together with the ORM? So far it seems to me that eventsourcing stuff is separate from Django ORM and this package just helps with setting up the runner inside of Django. Isn't eventsourcing a totally different model from Django ORM? How would you use models and perhaps DRF-style serializers/viewsets with this?

**Comment by johnbywater** [comment]
Hi sorry for the delay! The Django ORM is used for the event sourcing persistence model, that is for the stored events. This means that the code can be used in the same way as any Django app: with a range and databases and configured through settings. Hope that helps?

https://github.com/pyeventsourcing/eventsourcing-django/blob/main/eventsourcing_django/models.py
