### ISSUE TITLE
Creating a view off the events

### ISSUE THREAD

**Issue by Wintersina** [pyeventsourcing/eventsourcing-django#20]
Dear @johnbywater, and other maintainers.  wonderful project and i work with it daily.

I needed help understanding if there is a built in solution for creating a view off of events. 
we display our events in a list format for debugging and other senerios like so:
```
    def get_events(
        self, event_type: Aggragate.Event | UnionType | None = None
    ) -> list[Aggragate.Event]:
        my_agg = self.aggragate
        if not my_agg:
            return []

        return [
            event
            for event in self.application.events.get(originator_id=my_agg.id)
            if event_type is None or isinstance(event, event_type)
        ]
 ```

however, was wondering if there are some suggestions on
-  how we can transpose the events and its dataclasses into a view
-  how can we reply an aggregate to a given time.
- to see events in a timeline list in a more readable way.
 
goes without say, wonderful project and much appreciate all the love and hard work that went into it.

**Comment by johnbywater** [comment]
Hi @Wintersina! Thanks for your kind and generous remarks, and for your interest in and usage of this project.

The short answer to your question is that there isn't a built in solution for creating views, but there are some examples. The general idea is to work backwards: define the query you want to support, then define the database table that would support this query, and then write a policy which updates this table by processing events. The event processing policy can be defined as a `policy()` method on a `FollowerApplication`, with a system defined and run with the `System` and the system runner classes. But there are other ways of doing it.

I don't fully understand what you mean by "reply an aggregate to a given time".

If you want to see events in a timeline list, then you need to identify the query that would support this view would select events sorted by a timestamp, and so there would need to be a table that at least has a timestamp column, probably having all the other information for the stored event would be useful. It depends what you want to see in your timeline view.

I hope that helps? If you have any further questions or issues, please don't hesitate to ask.

**Comment by johnbywater** [comment]
> "reply an aggregate to a given time"

Did you mean "replay an aggregate to a given time"? In other words, select events for an aggregate up to a a given time and then reconstruct the aggregate from those events?

If so, there isn't a "built in" way to do this. But you could define this method on your application class:

```
    def get_aggregate_at(self, aggregate_id: UUID, timestamp: datetime) -> Aggregate:
        events = []
        for event in self.repository.event_store.get(aggregate_id):
            assert isinstance(event, Aggregate.Event)
            if event.timestamp > timestamp:
                break
            events.append(event)
        aggregate = project_aggregate(None, events)
        if aggregate is None:
            raise AggregateNotFoundError
        return aggregate
```

That would retrieve all events, and then avoid using events after a given date-time. That's probably the simplest implementation, but would involve retrieving events that are not used to reconstruct the required aggregate state.

A more complex alternative would be to project all events into a table that has originator ID, originator version, and timestamp columns, index the table by originator ID and timestamp, select the max originator ID for rows that have a given originator ID and timestamp less than a given value, and then use the result to get the aggregate at that version from the application repository.

**Comment by Wintersina** [comment]
> Did you mean "replay an aggregate to a given time"? In other words, select events for an aggregate up to a a given time and then reconstruct the aggregate from those events?

yes this is what I meant, thank you for the detailed response. I'll review with the team and follow up on any questions. 
i didnt mean for it to turn into a feature request! hahah

**Comment by Wintersina** [comment]
oh and `project_aggregate` works great 
![chefkiss](https://github.com/pyeventsourcing/eventsourcing-django/assets/15892509/edfea274-4dd3-40b8-a785-defbb31340af)

**Comment by Wintersina** [comment]
just wanted to share out take on how we ended up maintaining a view to hold snapshots of the current state, for those in the future who many wanna do something similar. 


`
    def log_event(self, event: str, **event_kwargs) -> Aggregate | None:

        try:
            self.application.handle_event(event=event, **event_kwargs)
        except AggregateNotFound:
            self.application.handle_event(
                event=EventApplication.Events.INITIALIZE
                var1=self.var1,
                initial_details=self.generate_inital_details(),
                initial_details2=self.generate_inital_details2(),
            )
            
            self.application.handle_event(event=event, **event_kwargs)
        finally:

            agg = self.aggregate  
            # persist current_state into a view
            if isinstance(agg, Aggregate):
                AggregateSnapshot.objects.create(
                    originator_id=agg.id,
                    version_number=agg.version,
                    event=event,
                    # and any other info we wanna keep

                )
            return agg
`
